travis:
  secure:
    BINSTAR_TOKEN: nL0jO3W8M7ajLLvg01Avq2hrTlyQVUB5B5WDXezDLOGSm1jqTwb6D1pLlh3ghZHxWQVSoPPZKpao+UtZeNtQUABLv5vCvGJvg+6WkYlLQfiwGdJiqU0or8OhTzrnR0vToShgGfLPMp23X2F1cw94/gk5L4H0Jiq9Cyro2cDOPJIGucCTIdsKmQ5oeUu4EPvVtv912SqmrJSUSmxIFAAU7v0fT7TjLvLsJsUypkJns1Mu0g6CvdJ74aA1RoxJj/th/BIOC0PuW2TF4KSrgChAMIhr/1P5SAMEYXn5eD+DHxpMj749ELqfUU0dj8CSJOyc60pJlX/2CQyKCBaHJ7mKXm5e8fmc4eQKyx+oH4iZ4X3ZZQG/AZ/Uh2hIPOhw1B+wqYfZCfpAD0WoDLo4+kz7goNIOiufaSaj6D9e0mnPWcDNLD6gEXwhqjpCnvVpEmkobj2w7L4Uif5FFr5ckWUaSPF5oD0IAegAzcszYgqkGi7bPLA94zLIUWAqaDjG/T/EYg2VBFIBsM4JZPiVjshamY/x6VFac93EXB8N9IsJ6nJFfNGWuxLQnfS3aLjycXDM9ryOoHyiYnWI8qWOPeK5n1MxkzYN8RGiDXCsAVdl4EcoCrEX44MFLveT+aRE3Ed0ThMrrjYmkzvl/qL8u2Xky/Zl8wLwhf2sFNWkX4d82HU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
